language: java
deploy:
  provider: heroku
  api_key:
    secure: CPON4/sG+E55dzafEkl78x0QscM5ht5mBmfCiUtR5/XKzFqb5FCPA7eejbGz2YxN4nzH4u2Zk0l6lVBzVxSSzdJ6AKOC5gY2VLoQopPK6s8SnzMa3mPDJCa7N9X42uYEo8CFHrMz7xliERlUno8g0LWVQJ0LhVRg6B403lN5AJzpW6ntQw4+VAkbhP6BapYfQpvZ1MSHOGU/PPsQHIWm8umalCAQpl4Sur6qSDl4Z+lhf/HTH+ggOcMbgYMcHGGjH2bZJh+KcxEzidzwF3r8eHqMFfW9V3Wf1fs16tZtX8g8THJSF4BaJ4R2vUaE8SiAGkxPM4Cpals0eoCnnPtVagTQM5vs7BFWWY367KeLvXorDzi7aFq2zVidQlMgiuY1k5Z81DOdypnDlqkp/xBeq1qAp6iOQytmLGcn3+Ixf+v6WUZ+N8SogEq6x5cGmYzJ+3AjH95dHwvdHFis/sla0sA1ENyK+3x8QerBQPZDX9vd28g2fGz2TfElwC2yx10NlgLw0iWQ1SLKfxoGdB4dsswDTj7gLGVoSyVs03YeZyPH6c0eodBW1IGRmt6F3gWmN6wjnVX5lN9cbZZaQXz2fWZFU/7g2laVkqKcIZxly6Tj87FOm6HGbSiBV/l7cUGiPhix0m8LnJg4LzhfxFJFFPojkRad8vVzwVoxeFrBSxk=
branches:
  only:
    - master